import Head from 'next/head'
import prisma from '../lib/prisma';

import { GetServerSideProps} from 'next';
import { Prisma } from '@prisma/client';

type Mission_ans = {gallery:[Prisma.mission_answerUncheckedCreateInput]}

export default function Gyallery(gallery: Mission_ans){
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
  
            <header>
                <h1 className="headline">あいづたんさクイズ</h1>
            </header>

            <br></br>
            {gallery.gallery.map(gyallery => (
                (gyallery.answer_image)?
                <div key={gyallery.id}>
                    <img
                    alt=''
                    src={gyallery.answer_image}
                    />
                    <br></br>
                </div>:
                <div key={gyallery.id}>
                    <p>{gyallery.answer_text}</p>
                </div>
            ))}
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async () => {
    const gallery = await prisma.mission_answer.findMany();
    //console.log(gallery)
    return {props: {gallery}}
}