import Head from 'next/head';
import prisma from '../lib/prisma';

import { Prisma } from '@prisma/client';

import { GetServerSideProps } from 'next';

type UserTable = { feed: [Prisma.user_tableUncheckedCreateInput] }
type MissionTable = { mission: [Prisma.missionUncheckedCreateInput] }

export default function Home(feed: MissionTable) {
  console.log(feed.mission[0].mission_id)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1 className="headline">あいづたんさクイズ</h1>
      </header>
      <br></br>
      <mark>ミッション一覧</mark>
      <br></br>
      {feed.mission.map(mission => (
        <div key={mission.mission_id}>
          <a href={`/${mission.mission_id}/`} className='btn-box-white' style={{ marginTop: '16px' }}>
            {mission.mission_statement}
            <div>{mission.mission_point}pt</div>
          </a>
          <br></br>
        </div>
      ))}
    </>
  )
}

// ページへ初回アクセス時実行する
export const getServerSideProps: GetServerSideProps = async () => {

  // user_tableの一覧を取得
  const feed = await prisma.user_table.findMany();
  console.log(feed)

  //missionの一覧を取得
  const mission = await prisma.mission.findMany();
  return { props: { mission } };
};
